theme = "ayu_evolve_t"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode"]
center = ["file-name"]
right = ["position-percentage", "spinner", "diagnostics", "workspace-diagnostics"]

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
parents = false

